config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :contractors
  resources :users
  resources :work_areas
  resources :check_list_items
  resources :check_lists
  resources :contractor_types
  resources :projects do 
    resources :inspeccions
  end
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end	
  	end
  end	
  get 'inspeccions', to:'inspeccions#index', as:'inspeccions'
  post "/inspeccions", to: 'inspeccions#create'
  get 'contractors/:id/api', to: 'contractors#api', as: 'api'
   get 'projects/:id/api_v1', to: 'projects#api_project', as: 'api_v1'
  root'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_many :check_list
  has_many :projects
  has_many :contractors
  has_many :inspeccions
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  has_many :check_list_items, dependent: :destroy
  accepts_nested_attributes_for :check_list_items,
    reject_if: proc { |attributes| attributes['text'].blank? },
    allow_destroy: true
  has_one :work_area, dependent: :destroy
  accepts_nested_attributes_for :work_area,
    reject_if: proc { |attributes| attributes['name'].blank? },
    allow_destroy: true
  has_many :todo_lists
  belongs_to :inspeccion, :optional => true
  validates :hazard_type, presence: true
 
  
end

app/models/check_list_item.rb
class CheckListItem < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :text, presence: true

  
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
  has_many :contractor_types, dependent: :destroy
  accepts_nested_attributes_for :contractor_types,
     reject_if: proc { |attributes| attributes['text'].blank? },
     allow_destroy: true
  has_many :check_lists, dependent: :destroy
  belongs_to :user, :optional => true
  validates :name, presence: true
  

end

app/models/contractor_type.rb
class ContractorType < ApplicationRecord
  belongs_to :contractor, :optional => true
  validates :name, presence: true

end

app/models/inspeccion.rb
class Inspeccion < ApplicationRecord
  has_many :check_lists, dependent: :destroy
  belongs_to :project, :optional => true
  belongs_to :contractor, :optional => true
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
   belongs_to :user, :optional => true

  
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
  	!completed_at.blank?
  end	
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :check_list
	has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_one_attached :profile_picture 
  has_many :projects, dependent: :destroy
  has_many :inspeccions, dependent: :destroy
  has_one :contractor
 
  
         
end

app/models/work_area.rb
class WorkArea < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :name, presence: true

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
    @check_lists = CheckList.all
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Check list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Check list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Check list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :check_list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inspeccions_helper.rb
module InspeccionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    def checked(project, area)
        
        project.periodicity.nil? ? false : project.periodicity.match(area)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_areas_helper.rb
module WorkAreasHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model:@todo_list,local:true) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this Check_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field" style="color:blue">
    <%= f.label :Check_list %>
    <%= f.select :check_list_id, options_from_collection_for_select(@check_lists, :id, :hazard_type)%>
  </div>

  <div class="field" style="color:black">
    <%= f.label :New_Check_List %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field" style="color:black">
    <%= f.label :Subtitle_Description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Check List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">	
	<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
    <div class="index_row clearfix container" style="background-repeat: no-repeat;background-position: center center;background-size: auto; background-image: url('https://images.pexels.com/photos/4161604/pexels-photo-4161604.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1450');" >    <div class="d-flex p-2">

        <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
        <p class="todo_list_sub_title"><%= todo_list.description %></p>
    </div>
              <% end %>    
            
<div class="links4" >
  <%= link_to "New Free Style Check List", new_todo_list_path %>
</div>
<div class="links3" >
<%= link_to 'Back', check_lists_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title2" style="color:white">New Check List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links2">	
	<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive shadow text-center"style="background-repeat: no-repeat;background-position: center center;background-size: auto; background-image: url('https://images.pexels.com/photos/2036686/pexels-photo-2036686.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1500');" >    <div class="d-flex p-2">
  <div class="container-fluid" >                  
    <table class="table table-index">
      <thead class="thead-dark">
        <tr class="text-center">
					 <th scope="col"><h2 class="todo_list_title"><%= @todo_list.title %></h2></th>
					<th scope="col"><p class="todo_list_sub_title"><%= @todo_list.description %></p></th>
 
        </tr>
      </thead>
    </table>
  </div>
</div>
<div id= "todo_items_wrapper">
	<%= render @todo_list.todo_items %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>	
</div>	

<div class="links">
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |
	<%= link_to 'Back', todo_lists_path %>

</div>