config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :contractors
  resources :users
  resources :work_areas
  resources :check_list_items
  resources :check_lists
  resources :contractor_types
  resources :projects do 
    resources :inspeccions
  end
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end	
  	end
  end	
  get 'inspeccions', to:'inspeccions#index', as:'inspeccions'
  post "/inspeccions", to: 'inspeccions#create'
  get 'contractors/:id/api', to: 'contractors#api', as: 'api'
   get 'projects/:id/api_v1', to: 'projects#api_project', as: 'api_v1'
  root'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_many :check_list
  has_many :projects
  has_many :contractors
  has_many :inspeccions
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  has_many :check_list_items, dependent: :destroy
  accepts_nested_attributes_for :check_list_items,
    reject_if: proc { |attributes| attributes['text'].blank? },
    allow_destroy: true
  has_one :work_area, dependent: :destroy
  accepts_nested_attributes_for :work_area,
    reject_if: proc { |attributes| attributes['name'].blank? },
    allow_destroy: true
  has_many :todo_lists
  belongs_to :inspeccion, :optional => true
  validates :hazard_type, presence: true
 
  
end

app/models/check_list_item.rb
class CheckListItem < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :text, presence: true

  
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
  has_many :contractor_types, dependent: :destroy
  accepts_nested_attributes_for :contractor_types,
     reject_if: proc { |attributes| attributes['text'].blank? },
     allow_destroy: true
  has_many :check_lists, dependent: :destroy
  belongs_to :user, :optional => true
  validates :name, presence: true
  

end

app/models/contractor_type.rb
class ContractorType < ApplicationRecord
  belongs_to :contractor, :optional => true
  validates :name, presence: true

end

app/models/inspeccion.rb
class Inspeccion < ApplicationRecord
  has_many :check_lists, dependent: :destroy
  belongs_to :project, :optional => true
  belongs_to :contractor, :optional => true
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
   belongs_to :user, :optional => true

  
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
  	!completed_at.blank?
  end	
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :check_list
	has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_one_attached :profile_picture 
  has_many :projects, dependent: :destroy
  has_many :inspeccions, dependent: :destroy
  has_one :contractor
 
  
         
end

app/models/work_area.rb
class WorkArea < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :name, presence: true

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    def checked(project, area)
        
        project.periodicity.nil? ? false : project.periodicity.match(area)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_areas_helper.rb
module WorkAreasHelper
end

app/views/shared/_footer.html.erb
 <footer class=" text-black ">
        <div class="container">
            <div class="row">
                <div class="col-2">
                <img src="<%= asset_path 'logo-SAFETY-SOLUTIONS-CR_1.png' %>" class= "footer-icon">
                   <!-- <h5 class="text-nowrap ml-5 text-left">Safety Solutions App</h5>-->
                </div>
                <div class="col-8">
                    <div class="justify-content-between text-rigth py-2 mr-0">
                         <i class="fab fa-github-square fa-2x pl-2"></i> 
                        <i class="fab fa-linkedin fa-2x pl-2"></i>
                        <i class="fab fa-twitter-square fa-2x pl-2"></i>
                        <i class="fab fa-facebook fa-2x pl-2"></i>
                    </div>
                </div>
            </div>
        </div>
</footer>

<!--
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-4 col-md-6 footer-info">
                    <h3>Econsulting</h3>
                    <p>Programando el futuro!!</p>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Menu</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Terms of service</a></li>
                        <li><a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Contáctanos</h4>

                    <div class="social-links">
                        <a href="https://www.facebook.com/EConsultingcr/" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="https://api.whatsapp.com/send?phone=50672610749" target="_blank" class="whatsapp"><i class="fa fa-whatsapp"></i></a>
                    </div>

                </div>

                <div class="col-lg-3 col-md-6 footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit"  value="Subscribe">
                    </form>
                    </div> 

            </div>
        </div>
    </div>
</footer>

 -->

app/views/shared/_footerhome.html.erb
<!-- Start Footer -->
<div id="contact">
    <footer class="footer-box-home ">
        <div class="container-fluid ">
            <div class="row ">
                <div class="col-xl-6 white_fonts ">
                    <div class="row ">
                        <div class="col-md-12 white_fonts margin-bottom_20 ">
                            <h3>Contactanos</h3>
                        </div>
                        <div class="col-md-12 " style="display: inline-flex ">
                            <div class="full-home icon-home ">
                                 <img src="<%=asset_path('social1.png') %>" alt="...">
                            </div>
                            <div class="full-home white_fonts ">
                                <p>Tibas, San Jose, Costa Rica</p>
                            </div>
                        </div>
                        <div class="col-md-12 " style="display: inline-flex ">
                            <div class="full-home icon-home ">
                                <img src="<%=asset_path('social2.png') %>" alt="...">
                            </div>
                            <div class="full-home white_fonts ">
                                <p>safetysolutioncr@gmail.com , infosscr@gmail.com</p>
                            </div>
                        </div>
                        <div class="col-md-12 " style="display: inline-flex ">
                            <div class="full-home icon-home ">
                                <img src="<%=asset_path('social3.png') %>" alt="...">
                            </div>
                            <div class="full-home white_fonts ">
                                <p>+50672037464 >+50672037464</p>
                            </div>
                        </div>
                        <div class="col-md-12 ">

                        </div>
                    </div>
                </div>

                <div class="col-xl-6 white_fonts ">
                    <div class="row ">
                        <div class="col-md-3 ">
                            <div class="footer_blog-home footer_menu-home ">
                                <h3>Menus</h3>
                                <ul>
                                    <li><a href="index.html ">Inicio</a></li>
                                    <li><a href="about.html ">Quienes Somos</a></li>
                                    <li><a href="services.html ">Servicios</a></li>
                                    <li><a href="app.html">App Safety CR</a></li>
                                    <li><a href="contact.html ">Contactanos</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-7 ">
                            <div class="footer_blog-home full-home ">
                                <h3 style= display:inline>Suscribete a nuestros servicios</h3>
                                <div class="newsletter_form-home ">
                                    <form action="index.html ">
                                        <input type="email " placeholder="Your Email " name="# " required/>
                                        <button>Enviar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </footer>
    <!-- End Footer -->

    <div class="footer_bottom-home ">
        <div class="container ">
            <div class="row ">
                <div class="col-12 ">
                    <p class="crp-home ">© 2021 safetysolutioncr, Todos los derechos reservados.</p>
                    <ul class="bottom_menu-home ">
                        <li><a href="# "><i class="fa fa-facebook-f "></i></a></li>
                        <li><a href="# "><i class="fa fa-twitter "></i></a></li>
                        <li><a href="# "><i class="fa fa-linkedin "></i></a></li>
                        <li><a href="# "><i class="fa fa-google-plus "></i></a></li>
                        <li><a href="# ">Terminos de servicio</a></li>
                        <li><a href="# ">Privacidad</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="redes-sociales-home ">
        <ul class="list-group-home text-center text-white ">
            <li class="list-group-item-home ">
                <a data-toggle="tooltip " data-placement="left " title=" " href="# " target="_blank " class="text-white " data-original-title="Siguenos a nuestra comunidad de Facebook ">
                     <img src="<%=asset_path('facebook.png') %>" class="" width="35 " alt="#">
            </li>
            <li class="list-group-item-home ">

                 <img src="<%=asset_path('icons8-twitter-48.png') %>" class="" width="35 "  alt="#">
            </li>
            <li class="list-group-item-home ">
                  <img src="<%=asset_path('icons8-instagram-48.png') %>" class="" width="35 "  alt="#">
            </li>
            <li class="list-group-item-home ">
                <img src="<%=asset_path('icons8-youtube-play-48.png') %>" class="" width="35 "  alt="#">
            </li>
            <li class="list-group-item-home ">
                <a target="_blank " href="https://api.whatsapp.com/send?phone=+50672037464&amp;text=Estoy interesado en tomar tu solicitud de servicios de salud ocupacional "><img src="<%=asset_path('icons8-whatsapp-48.png') %>" class="" width="35 "  alt="#">
            </li>

        </ul>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="relative bg-white ">
  <nav class="navbar_menu">
    <%= link_to root_path do %>
        <span class="sr-only">Workflow</span>
        <%= image_tag "safety_sol.png", id:'logot', alt: "logo", class: "logo h-8 w-auto sm:h-10" %>
    <% end %>

  

    <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->
        <ul class="navbar_menu_items">
              <li class="nav-item nav-link"> <%=link_to "Home", root_path, :class => "inicionav"%><a href="#inicio"></a></li>
               
               
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Menu</a>
                <div class="dropdown-menu">
                    <%= link_to 'Projects', projects_path, class: "dropdown-item" %>
                    <%= link_to 'Contractors', contractors_path, class: "dropdown-item" %>
                    <%= link_to 'Inspeccions', inspeccions_path, class: "dropdown-item" %>
                    <%= link_to 'Check list', check_lists_path, class: "dropdown-item" %>
                </div>
          
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Go to</a>
              <div class="dropdown-menu">
                <%= link_to "Go to new Projects", new_project_path, class: "dropdown-item" %>
                <%= link_to "Go to new contractors", new_contractor_path, class: "dropdown-item" %>
                 <%= link_to "Go to new check", todo_lists_path, class: "dropdown-item" %>
            
                <%#= link_to "ir a Inspeccions", new_project_inspeccion_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="center">
                <% if user_signed_in? %>
                    <%= link_to 'Logout', destroy_user_session_path, method: "delete"  %>

                <% else %>
                    <%= link_to 'Login', new_user_session_path, class: "a" %>
                <% end %>

                <% if current_user %>
                    <%= link_to(edit_user_registration_path) do %>
                    <% if current_user.profile_picture.attached?  %>
                        <%= image_tag(current_user.profile_picture, class: 'avatar-img') %>
                     <% end %>
                    <% end %>
                <% end %> 
            </li>
            
        </ul>
      <span class="btn_menu">
          <i class="fa fa-bars"></i>
      </span>
  </nav>
      
    
</div>

app/views/shared/_navbarhome.html.erb
<div class="relative bg-white ">
  <nav class="navbar_menu_home">
    <%= link_to root_path do %>
        <span class="sr-only">Workflow</span>
        <%= image_tag "safety_sol.png", alt: "logo", class: "logo h-8 w-auto sm:h-10" %>
    <% end %>

  

    <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->
        <ul class="navbar_menu_items">
             
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">INICIO</a>
                  <ul class="navbar-nav">
                      <li id="inicio"><%#=link_to "Inicio", index_path, :class => "inicionav"%></li> 
                  </ul>
               <a href="#about">about </a>          
               
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">NUESTROS SERVICIOS</a>
                    <div class="dropdown-menu">
                       <ul class="navbar-nav"> 
                        <li id="services"><%#=link_to "Services", services_path, :class => "servicesnav"%></li> 
                        </ul>
                      </div>    
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">APP SAFETY SOLUTIONS CR</a>
                <div class="dropdown-menu">
                    <%= link_to 'Projects', projects_path, class: "dropdown-item" %>
                    <%= link_to 'Contractors', contractors_path, class: "dropdown-item" %>
                    <%= link_to 'Inspeccions', inspeccions_path, class: "dropdown-item" %>
                    <%= link_to 'Check list', check_lists_path, class: "dropdown-item" %>
                </div>
          
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">CONTACTO</a>
              <ul class="navbar-nav"> 
                <li id="contact"><%#=link_to "Contact", contacts_path, :class => "contactnav"%></li>
               </ul>
              </div>
            </li>
            <li class="center">
                <% if user_signed_in? %>
                    <%= link_to 'Logout', destroy_user_session_path, method: "delete"  %>

                <% else %>
                    <%= link_to 'Login', new_user_session_path, class: "a" %>
                <% end %>

                <% if current_user %>
                    <%= link_to(edit_user_registration_path) do %>
                    <% if current_user.profile_picture.attached?  %>
                        <%= image_tag(current_user.profile_picture, class: 'avatar-img') %>
                     <% end %>
                    <% end %>
                <% end %> 
            </li>
            
        </ul>
      <span class="btn_menu">
          <i class="fa fa-bars"></i>
      </span>
  </nav>
      
    
</div>
 

app/views/shared/home_side/_carousel.html.erb
<div class="container-fluid" style="padding-top: 0%; margin: 20px">
  <div style="position: container; width: 100%;">
          <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="<%=asset_path('banner5.jpg') %>" class="d-block w-1050" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
            </div>
              <div class="carousel-item">
                <img src="<%=asset_path('banner3.jpg') %>" class="d-block w-1050" alt="...">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
              </div>
                <div class="carousel-item">
                  <img src="<%=asset_path('banner7.jpg') %>" class="d-block w-1050" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Third slide label</h5>
                          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                    </div>
                </div>
            </div>
              <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
    </div>
  </div>
</div>