config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :contractors
  resources :users
  resources :work_areas
  resources :check_list_items
  resources :check_lists
  resources :contractor_types
  resources :projects do 
    resources :inspeccions
  end
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end	
  	end
  end	
  get 'inspeccions', to:'inspeccions#index', as:'inspeccions'
  post "/inspeccions", to: 'inspeccions#create'
  get 'contractors/:id/api', to: 'contractors#api', as: 'api'
   get 'projects/:id/api_v1', to: 'projects#api_project', as: 'api_v1'
  root'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_many :check_list
  has_many :projects
  has_many :contractors
  has_many :inspeccions
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  has_many :check_list_items, dependent: :destroy
  accepts_nested_attributes_for :check_list_items,
    reject_if: proc { |attributes| attributes['text'].blank? },
    allow_destroy: true
  has_one :work_area, dependent: :destroy
  accepts_nested_attributes_for :work_area,
    reject_if: proc { |attributes| attributes['name'].blank? },
    allow_destroy: true
  has_many :todo_lists
  belongs_to :inspeccion, :optional => true
  validates :hazard_type, presence: true
 
  
end

app/models/check_list_item.rb
class CheckListItem < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :text, presence: true

  
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
  has_many :contractor_types, dependent: :destroy
  accepts_nested_attributes_for :contractor_types,
     reject_if: proc { |attributes| attributes['text'].blank? },
     allow_destroy: true
  has_many :check_lists, dependent: :destroy
  belongs_to :user, :optional => true
  validates :name, presence: true
  

end

app/models/contractor_type.rb
class ContractorType < ApplicationRecord
  belongs_to :contractor, :optional => true
  validates :name, presence: true

end

app/models/inspeccion.rb
class Inspeccion < ApplicationRecord
  has_many :check_lists, dependent: :destroy
  belongs_to :project, :optional => true
  belongs_to :contractor, :optional => true
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
   belongs_to :user, :optional => true

  
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
  	!completed_at.blank?
  end	
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :check_list
	has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_one_attached :profile_picture 
  has_many :projects, dependent: :destroy
  has_many :inspeccions, dependent: :destroy
  has_one :contractor
 
  
         
end

app/models/work_area.rb
class WorkArea < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :name, presence: true

end

app/controllers/check_list_items_controller.rb
class CheckListItemsController < ApplicationController
  before_action :set_check_list_item, only: %i[ show edit update destroy ]
  before_action :set_check_list, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :authenticate_user!, except: []  
  # GET /check_list_items or /check_list_items.json
  def index
    @check_list_items = CheckListItem.all.order(:value)
  end

  # GET /check_list_items/1 or /check_list_items/1.json
  def show
  end

  # GET /check_list_items/new
  def new
    @check_list_item = CheckListItem.new
    @check_list = CheckList.all
  end

  # GET /check_list_items/1/edit
  def edit
    @CheckList.build
  end

  # POST /check_list_items or /check_list_items.json
  def create
    @check_list_item = CheckListItem.new(check_list_item_params)
    @check_list = CheckList.all

    respond_to do |format|
      if @check_list_item.save
        format.html { redirect_to @check_list_item, notice: "Check list item was successfully created." }
        format.json { render :show, status: :created, location: @check_list_item }
      else
        format.html { render :new }
        format.json { render json: @check_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_list_items/1 or /check_list_items/1.json
  def update
    respond_to do |format|
      if @check_list_item.update(check_list_item_params)
        format.html { redirect_to @check_list_item, notice: "Check list item was successfully updated." }
        format.json { render :show, status: :ok, location: @check_list_item }
      else
        format.html { render :edit }
        format.json { render json: @check_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_list_items/1 or /check_list_items/1.json
  def destroy
    @check_list_item.destroy
    respond_to do |format|
      format.html { redirect_to check_list_items_url, notice: "Check list item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_list_item
      @check_list_item = CheckListItem.find(params[:id])
    end
    
    def set_check_list
      @check_list = CheckList.find(params[:id])
      
    end
    # Only allow a list of trusted parameters through.
    def check_list_item_params
      params.require(:check_list_item).permit(:value, :text, :check_list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/check_list_items_helper.rb
module CheckListItemsHelper
end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    def checked(project, area)
        
        project.periodicity.nil? ? false : project.periodicity.match(area)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_areas_helper.rb
module WorkAreasHelper
end

app/views/check_list_items/_form.html.erb
<%= form_with(model: check_list_item) do |form| %>
  <% if check_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check_list_item.errors.count, "error") %> prohibited this check_list_item from being saved:</h2>

      <ul>
        <% check_list_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="color:white">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field" style="color:white">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field" style="color:white">
    <%= form.label :check_list %>
    <%= form.select :check_list_id, options_from_collection_for_select(@check_list, :id, :hazard_type)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/check_list_items/edit.html.erb
<h1>Editing Check List Item</h1>

<%= render 'form', check_list_item: @check_list_item %>

<%= link_to 'Show', @check_list_item %> |
<%= link_to 'Back', check_list_items_path %>

app/views/check_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center mt-5 mb-2" style="color:white">Check List Items</h1>

<table class="table table-index">
   <thead class="thead-dark">
    <tr class="text-center">
      <th scope="col">Value</th>
      <th scope="col">Text</th>
      <<th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @check_list_items.each do |check_list_item| %>
      <tr class="text-center">
        <td style="color:white"><%= check_list_item.value %></td>
        <td style="color:white"><%= check_list_item.text %></td>
          <% if admin_signed_in? %>  
        <td style="background-color:white"><%= link_to 'Show', check_list_item %></td>
        <td style="background-color:white"><%= link_to 'Edit', edit_check_list_item_path(check_list_item) %></td>
        <td style="background-color:white"><%= link_to 'Destroy', check_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="btn btn-dark">New Check List item</button>'.html_safe, new_check_list_item_path %>
<%= link_to '<button type="button" class="btn btn-dark">New Check List</button>'.html_safe, new_check_list_path %>

app/views/check_list_items/new.html.erb
<h1>New Check List Item</h1>

<%= render 'form', check_list_item: @check_list_item %>

<%= link_to 'Back', check_list_items_path %>

app/views/check_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p style="color:white">
  <strong>Value:</strong>
  <%= @check_list_item.value %>
</p>

<p style="color:white">
  <strong>Text:</strong>
  <%= @check_list_item.text %>
</p>

<%= link_to 'Edit', edit_check_list_item_path(@check_list_item) %> |
<%= link_to 'Back', check_list_items_path %>