config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :contractors
  resources :users
  resources :work_areas
  resources :check_list_items
  resources :check_lists
  resources :contractor_types
  resources :projects do 
    resources :inspeccions
  end
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end	
  	end
  end	
  get 'inspeccions', to:'inspeccions#index', as:'inspeccions'
  post "/inspeccions", to: 'inspeccions#create'
  get 'contractors/:id/api', to: 'contractors#api', as: 'api'
   get 'projects/:id/api_v1', to: 'projects#api_project', as: 'api_v1'
  root'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_many :check_list
  has_many :projects
  has_many :contractors
  has_many :inspeccions
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  has_many :check_list_items, dependent: :destroy
  accepts_nested_attributes_for :check_list_items,
    reject_if: proc { |attributes| attributes['text'].blank? },
    allow_destroy: true
  has_one :work_area, dependent: :destroy
  accepts_nested_attributes_for :work_area,
    reject_if: proc { |attributes| attributes['name'].blank? },
    allow_destroy: true
  has_many :todo_lists
  belongs_to :inspeccion, :optional => true
  validates :hazard_type, presence: true
 
  
end

app/models/check_list_item.rb
class CheckListItem < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :text, presence: true

  
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
  has_many :contractor_types, dependent: :destroy
  accepts_nested_attributes_for :contractor_types,
     reject_if: proc { |attributes| attributes['text'].blank? },
     allow_destroy: true
  has_many :check_lists, dependent: :destroy
  belongs_to :user, :optional => true
  validates :name, presence: true
  

end

app/models/contractor_type.rb
class ContractorType < ApplicationRecord
  belongs_to :contractor, :optional => true
  validates :name, presence: true

end

app/models/inspeccion.rb
class Inspeccion < ApplicationRecord
  has_many :check_lists, dependent: :destroy
  belongs_to :project, :optional => true
  belongs_to :contractor, :optional => true
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :inspeccions, dependent: :destroy
   belongs_to :user, :optional => true

  
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
  	!completed_at.blank?
  end	
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :check_list
	has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_one_attached :profile_picture 
  has_many :projects, dependent: :destroy
  has_many :inspeccions, dependent: :destroy
  has_one :contractor
 
  
         
end

app/models/work_area.rb
class WorkArea < ApplicationRecord
  belongs_to :check_list, optional: true
  validates :name, presence: true

end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: %i[ show edit update destroy ]
   # before_action :authenticate_admin!, except: [:new, :create, :show, :index]
  before_action :set_contractor_type, only: %i[ show edit update destroy new ]
  before_action :authenticate_user!, except: %i[ index search ]
 
  # GET /contractors or /contractors.json
  def index
    @contractors = Contractor.all.order(:name)
    @inspeccion = Inspeccion.all
    @contractor = Contractor.new
    @contractor.contractor_types.build    
    @contractor_types = ContractorType.all
  end

  def api
    c = Contractor.find(params[:id])
    hash = {
      name: Contractor.name,
      contractor_types_attributes:[:name]  
    }
    render json: hash
  end


  # GET /contractors/1 or /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @inspeccion = Inspeccion.all
    @contractor = Contractor.new
    @contractor.contractor_types.build
     
  end

  # GET /contractors/1/edit
  def edit
    @contractor.contractor_types.build
    @contractor_types = ContractorType.all    
  end

  # POST /contractors or /contractors.json
  def create
    @contractor = Contractor.new(contractor_params.merge(user: current_user)) 
    @inspeccion = Inspeccion.all
   
    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: "Contractor was successfully created." }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1 or /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: "Contractor was successfully updated." }
        format.json { render :show, status: :ok, location: @contractor }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1 or /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: "Contractor was successfully destroyed." }
      format.json { head :no_content }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    def typ_params
      params.require(:contractor_type)
    end

    # def contractor_types
    #   @contractor_type = ContractorType.all
    # end

    def set_contractor_type
      @contractor_type = ContractorType.all
    end
    def set_inspeccion    
      @inspeccion = Inspeccion.find(params[:inspeccion_id])
    end
    # Only allow a list of trusted parameters through.
    def contractor_params
      params.require(:contractor).permit(:name, :inspeccion_id,:id, contractor_types_attributes: [:name] )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inspeccions_helper.rb
module InspeccionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    def checked(project, area)
        
        project.periodicity.nil? ? false : project.periodicity.match(area)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_areas_helper.rb
module WorkAreasHelper
end

app/views/contractors/_form.html.erb
<%= form_with(model: contractor, remote: true) do |form| %>
  <% if contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
        <% contractor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <h2 style="background-color:white">Contractor name:</h2>
  <div class="field" style="color:white">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <h2 style="background-color:white">Contractor types:</h2>
 
  <%= form.select :contractor_type_id, options_from_collection_for_select(@contractor_types, :id, :name)%>
  <%= form.fields_for :contractor_types do | type | %>
    <div class="contractor_types_fields">
      <div class="fields">
        <%= type.label "Type" %><br>
        <%= type.text_field :name %>
      </div>
    </div>
  <% end %>

   
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contractors/_row.html.erb
<tr id="<%= contractor.id %>">
  <td><%= contractor.name %></td>
  <td><%= contractor.contractor_types.map {|c| c.name}.join(", ") %></td>
  <td><%= contractor.inspeccions.map {|contractor| contractor.date}.join(", ") %></td>

  <td><%= link_to (fa_icon "edit"), edit_contractor_path(contractor), class: "btn btn-secondary btn-sm shadow", title: "Editar contratista", remote: true %></td>
  <td><%= link_to (fa_icon "trash"), contractor, method: :delete, data: { confirm: "¿Estas seguro de eliminar contratista"}, class: "btn btn-danger btn-sm shadow", title: "Eliminar " %></td>
</tr>

app/views/contractors/create.js.erb
<% if @contractor.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", contractor: @contractor %>');
  $('.alert-success').html("El contratista ha sido ingresada con éxito").show();
  $('#people-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @contractor.errors.full_messages[0] %>');
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing Contractor</h1>

<%= render 'form', contractor: @contractor %>


<%= link_to 'Back', contractors_path %>

app/views/contractors/edit.js.erb
$('<%= j render "form", contractor: @contractor,title: "Editar contratista" %>').on('hidden.bs.modal', function (e) {
    $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/contractors/index.html.erb
<p id="notice"><%= notice %></p>



<div class="container ">
  <div class="container" style="background-repeat: no-repeat;background-position: center center;background-size: auto; background-image: url('https://images.pexels.com/photos/4161604/pexels-photo-4161604.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1050');" >
    <div class="d-flex p-2">
      <%= fa_icon "question", class: "btn btn-info btn-sm shadow", title: "Aqui encontraras toda la informacion al respecto de los contratistas su nombre, y tipo, tambien puedes eliminar, editar y agregar un nuevo contratista" %>
      <h1 class="text-center mt-5 mb-2" style="color:black">Contractors</h1>
    </div>
    <div class="card-body">
      <div class="card-title d-flex justify-content-between align-items-center">
            <button type="button" class=" btn btn-primary " data-toggle="modal" data-target="#staticBackdrop">
                contractor new
            </button> 
               <%= link_to '<button type="button" class="btn btn-primary">Project</button>'.html_safe, projects_path %>
            <%= link_to '<button type="button" class="btn btn-primary">Contractor types </button>'.html_safe, contractor_types_path %>
      </div>
      <div class="table-responsive shadow text-center">
        <table class="table table-hover table-sm small">
          <thead class="thead-dark">
            <tr class="text-center">
              <th scope="col">Name</th>
              <th scope="col">Contractor Type</th>
               <th scope="col">Inspeccions</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
              <% @contractors.each do |contractor| %>
              <%= render "row", contractor: contractor %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>


<%#= link_to '<button type="button" class="btn btn-dark">Inspeccion type </button>'.html_safe, project_inspeccions_path %>


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"  style="background-image: url('https://cdn.pixabay.com/photo/2018/09/25/23/40/baukran-3703469__340.jpg');">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">New Contractor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%= render "form", contractor: @contractor %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>

<%= render 'form', contractor: @contractor %>


<%= link_to 'Back', contractors_path %>

app/views/contractors/new.js.erb
$('<%= j render "form", title: "Nuevo contratista" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contractor.name %>
</p>
<h2>contractor_type</h2>

<% if @contractor.contractor_types.any? %>
	    <ul>
		    <% @contractor.contractor_types.each do |type| %>
		      <li><%= link_to type, type %></li> 
	      <% end %>
    	</ul>
<% else %>
	      <p>no hay contractor_type</p>
<% end %>

<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/update.js.erb
<% if @contractor.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @contractor.id %>').replaceWith(' <%= j render "row", contractor: @contractor %>');
  $('.alert-success').html("El contratista ha sido editado con éxito").show();
  $('#people-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @contractor.errors.full_messages[0] %>');
<% end %>